apiVersion: apps/v1
kind: Deployment
metadata:
 lables:
   app: nginx
 name: nginx-deployment 
spec:
 replicas: 1
 selector:
   matchLables:
     app: nginx
 template:
   metadata:
     lables:
       app: nginx
   spec: 
    containers:
    - image: nginx
      name: nginx	
