apiVersion: v1
kind: Service
metadata:
        lables:
                app: nginx
               name: nginx-service
	  namespace: default
spec: 
	ports:
	- port: 80
	protocol: TCP
	targetPort: 80	
 selector:
	app: nginx
	type: NodePort
